apiVersion: v1
kind: Service
metadata:
  name: hello-kube
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello-kube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
      - name: hello-kube
        image: paulbouwer/hello-kubernetes:1.5
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from your k8s playground
---          
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-kube
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: playground.me
    http:
      paths:
      - backend:
          serviceName: hello
          servicePort: 80